server:
  port: 8006

spring:
  application:
    name: consoul-provider-payment
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}