server:
  port: 80

eureka:
  client:
    # 将自己注册进 EurekaServer?
    register-with-eureka: false
    # 从 EurekaServer 抓取已有的注册信息？
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka

logging:
  level:
    com.zfhczc.springcloud.service.PaymentFeignService: debug